### ISSUE TITLE
Storage reset broken in version 0.10.1?

### ISSUE THREAD

**Issue by florish** [commanded/eventstore#69]
I've been using `EventStore.Storage.Initializer.reset!/1` to reset the EventStore database between test runs. For version 0.9.0, this worked fine, but after upgrading, the reset triggers a `DBConnection` error.

IEx output below from a fresh `mix` app with only `{:eventstore, "~> 0.10.1"}` in deps and no further code added, except for default EventStore config from Getting Started in `config.exs`. Steps taken are the same as in the test helper used in the application where I first encountered the error.

To be sure: I'm entirely open to other suggestions for truncating / resetting the `eventstore` between database runs if that is easier than to fix this! I though it would be good to open this issue anyway in case this is a sign of something more severe.

IEx output:

```
iex(1)> :ok = Application.stop(:eventstore)
:ok

14:21:19.568 [info]  Application eventstore exited: :stopped
iex(2)> eventstore_config = Application.get_env(:eventstore, EventStore.Storage)
[serializer: EventStore.TermSerializer, username: "postgres",
 password: "postgres", database: "eventstore_reset_dev", hostname: "localhost",
 pool_size: 10, pool_overflow: 5]
iex(3)> {:ok, conn} = Postgrex.start_link(eventstore_config)
{:ok, #PID<0.208.0>}
iex(4)> EventStore.Storage.Initializer.reset!(conn)
** (EXIT from #PID<0.202.0>) evaluator process exited with reason: an exception was raised:
    ** (FunctionClauseError) no function clause matching in DBConnection.Connection.handle_call/3
        (db_connection) lib/db_connection/connection.ex:192: DBConnection.Connection.handle_call({:checkout, #Reference<0.2456580215.3043753987.104870>, true}, {#PID<0.202.0>, #Reference<0.2456580215.3043753987.104871>}, %{after_connect: nil, after_connect_timeout: 15000, after_timeout: :backoff, backoff: %DBConnection.Backoff{max: 30000, min: 1000, state: {1000, 10000, {:rand, {%{jump: #Function<16.15449617/1 in :rand.mk_alg/1>, max: 288230376151711743, next: #Function<15.15449617/1 in :rand.mk_alg/1>, type: :exsplus}, [248613990448091245 | 111711591027812860]}}}, type: :rand_exp}, broker: nil, client: nil, idle: :passive, idle_time: 0, idle_timeout: 1000, lock: nil, mod: Postgrex.Protocol, opts: [types: Postgrex.DefaultTypes, serializer: EventStore.TermSerializer, username: "postgres", password: "postgres", database: "eventstore_reset_dev", hostname: "localhost", pool_size: 10, pool_overflow: 5], queue: {[], []}, regulator: nil, state: %Postgrex.Protocol{buffer: "", connection_id: 90169, connection_key: 1883835500, null: nil, parameters: #Reference<0.2456580215.3043753987.104864>, peer: {{127, 0, 0, 1}, 5432}, postgres: :idle, queries: #Reference<0.2456580215.3043885059.104861>, sock: {:gen_tcp, #Port<0.5348>}, timeout: 15000, transactions: :naive, types: {Postgrex.DefaultTypes, #Reference<0.2456580215.3043885060.104801>}}, timer: nil})
        (connection) lib/connection.ex:488: Connection.handle_call/3
        (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by slashdotdash** [comment]
Thanks for the issue report. Sorry, I changed EventStore in v0.10 to use the connection pool provided by the Postgrex driver. 

To reset storage you need to include the `pool` config setting as shown in this reset function:

```elixir
  defp reset_eventstore do
    eventstore_config =
      Application.get_env(:eventstore, EventStore.Storage)
      |> Keyword.merge(pool: DBConnection.Poolboy)

    {:ok, conn} = Postgrex.start_link(eventstore_config)

    EventStore.Storage.Initializer.reset!(conn)
  end
```

I will update the documentation to include this information.

**Comment by slashdotdash** [comment]
@florish You can also use the following helper functions in Event Store to fetch & parse the config:

```elixir
config = EventStore.configuration() |> EventStore.Config.parse()
```

Which includes the `pool` setting for you.

**Comment by florish** [comment]
@slashdotdash Thanks! Your first code snippet resolves the issue for me. Didn't try the second one yet, but looks like a nice and clean approach!

**Comment by sebastialonso** [comment]
@slashdotdash I'm implementing the same snippet of code (and also following the Coundit book along with Commanded).

Versions of packages are listed below
~~~
Dependency resolution completed:
Unchanged:
  commanded 0.17.0
  commanded_ecto_projections 0.7.1
  **commanded_eventstore_adapter** 0.4.0
  connection 1.0.4
  cowboy 1.1.2
  cowlib 1.0.2
  db_connection 1.1.3
  decimal 1.5.0
  ecto 2.2.10
  *eventstore* 0.15.1
  ex_machina 2.2.0
  ....
~~~

When I try to run the tests this same error appears
~~~bash

  1) test register user should succeed with valid data (Conduit.AccountsTest)
     test/conduit/accounts/accounts_test.exs:9
     ** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
     stacktrace:
       :invalid_message.exception([])
       (db_connection) lib/db_connection.ex:934: DBConnection.checkout/2
       (db_connection) lib/db_connection.ex:750: DBConnection.run/3
       (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
       (conduit) test/support/data_case.ex:49: Conduit.DataCase.reset_eventstore/0
       (conduit) test/support/data_case.ex:35: Conduit.DataCase.__ex_unit_setup_0/1
       (conduit) test/support/data_case.ex:1: Conduit.DataCase.__ex_unit__/2
       test/conduit/accounts/accounts_test.exs:1: Conduit.AccountsTest.__ex_unit__/2
~~~

which I have routed back to the bolded line:
~~~elixir
{:ok, conn} =
    EventStore.configuration()
    |> EventStore.Config.parse()
    |> Postgrex.start_link()

    **EventStore.Storage.Initializer.reset!(conn)**
~~~

Any ideas what might be causing this issue?

**Comment by sebastialonso** [comment]
Maybe the book could be updated with this crucial piece of info?
